export const dummy1 = {
    "page":2,
    "results":[
        {
            "adult":false,
            "backdrop_path":"/7ABsaBkO1jA2psC8Hy4IDhkID4h.jpg",
            "genre_ids":[28,12,14,878],
            "id":19995,
            "original_language":"en",
            "original_title":"Avatar",
            "overview":"가까운 미래, 지구는 에너지 고갈 문제를 해결하기 위해 머나먼 행성 판도라에서 대체 자원을 채굴하기 시작한다. 하지만 판도라의 독성을 지닌 대기로 인해 자원 획득에 어려움을 겪게 된 인류는 판도라의 토착민 나비의 외형에 인간의 의식을 주입, 원격 조종이 가능한 새로운 생명체를 탄생시키는 프로그램을 개발한다. 한편 하반신이 마비된 전직 해병대원 제이크 설리는 아바타 프로그램에 참가할 것을 제안받는다. 그 곳에서 자신의 아바타를 통해 자유롭게 걸을 수 있게 된 제이크는 자원 채굴을 막으려는 나비의 무리에 침투하라는 임무를 부여받는데...",
            "popularity":648.095,
            "poster_path":"/zygmx5abXeDpr3fWYX4jlXFZ1wh.jpg",
            "release_date":"2010-08-26",
            "title":"아바타",
            "video":false,
            "vote_average":7.5,
            "vote_count":26316
        },
        {
            "adult":false,
            "backdrop_path":"/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
            "genre_ids":[16,10751,35,14],
            "id":508947,
            "original_language":"en",
            "original_title":"Turning Red",
            "overview":"엄마의 착한 딸, 아니면 미운 13살? 성적도 우수하고 친구들과 사이도 좋은 데다 부모와도 친밀한 관계를 유지하고 있는, 똑 부러지면서도 엉뚱한 매력의 소유자 메이는 요즘 질풍노도의 시기를 겪느라 고민이 많다. 이 나이에 엄마의 과잉보호를 받자니 스트레스가 이만저만이 아닌 데다, 관심사, 인간관계, 신체 등 그녀의 모든 것이 변하고 있기 때문. 그런데 이 와중에 흥분하면 거대한 레서판다로 변신하는 비밀까지 떠안게 되다니! 아침도 먹어야 하고 학교도 가야 하는데, 이 엄청난 비밀을 어떻게 숨겨야 할까?",
            "popularity":768.102,
            "poster_path":"/hsOhOcX7qDy7bPwbrt1OoITngrf.jpg",
            "release_date":"2022-03-11",
            "title":"메이의 새빨간 비밀",
            "video":false,
            "vote_average":7.5,
            "vote_count":3399
        },
        {
            "adult":false,
            "backdrop_path":"/3p3amyz5nXK9AW4VARqkPaMAG5J.jpg",
            "genre_ids":[16,12,35,14],
            "id":585511,
            "original_language":"en",
            "original_title":"Luck",
            "overview":"불운의 아이콘 '샘 그린필드'는 어디에서도 본 적 없는 운의 왕국을 우연히 발견하고, 가장 친한 친구에게 행운을 가져다주기 위해 그곳으로의 여행을 계획한다. 하지만 운의 왕국은 인간의 접근을 허락하지 않고, '샘 그린필드'는 여행을 실행에 옮기기 위한 유일한 방법으로 마법의 생명체들로부터 도움을 받게 된다.",
            "popularity":641.854,
            "poster_path":"/nN2iHej7TyISjXC6Jl577aqpDHJ.jpg",
            "release_date":"2022-08-05",
            "title":"럭",
            "video":false,
            "vote_average":8,
            "vote_count":799
        },
        {
            "adult":false,
            "backdrop_path":"/jzWT0zd8U77fqWg5WgUfYaMzSFz.jpg",
            "genre_ids":[28,878,14],
            "id":526896,
            "original_language":"en",
            "original_title":"Morbius",
            "overview":"희귀혈액병을 앓고 있는 생화학자 모비우스는 동료인 마르틴과 함께 치료제 개발에 몰두한다. 흡혈 박쥐를 연구하던 중 마침내 치료제 개발에 성공한 모비우스는 새 생명과 강력한 힘을 얻게 되지만, 동시에 흡혈을 하지 않고는 생명을 유지할 수 없게 된다. 그러던 중 모비우스와 같은 병을 앓고 있던 그의 친구 마일로도 모비우스와 같은 힘을 얻게 되는데…",
            "popularity":617.025,
            "poster_path":"/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg",
            "release_date":"2022-03-30",
            "title":"모비우스",
            "video":false,
            "vote_average":6.4,
            "vote_count":2726
        },
        {
            "adult":false,
            "backdrop_path":"/hwUxHPkuUleJeoick4uZsrKDXxF.jpg",
            "genre_ids":[16,28,12,10751,878],
            "id":718789,
            "original_language":"en",
            "original_title":"Lightyear",
            "overview":"나, 버즈 라이트이어. 인류 구원에 필요한 자원을 감지하고 현재 수많은 과학자들과 미지의 행성으로 향하고 있다. 이번 미션은 인류의 역사를 새롭게 쓸 것이라 확신한다. 잘못된 신호였다. 이곳은 삭막하고 거대한 외계 생물만이 살고 있는 폐허의 땅이다. 나의 실수로 모두가 이곳에 고립되고 말았다. 모두를 구하기 위해서 모든 것을 제자리에 돌려 놔야 한다. 실수를 바로잡기 위한 탈출 미션을 위해 1년의 준비를 마쳤다. 어쩌다 한 팀이 된 정예 부대와 이 미션을 수행할 예정이다. 우주를 집어삼킬 저그 황제와 대규모 로봇 군사의 위협이 계속되지만 나는 절대 포기할 수 없다. 그런데... 여긴 또 어디지? 시간 속에 갇힌 건가?",
            "popularity":717.02,
            "poster_path":"/oMa5NjFxK8Csp6uVQ0tRuF1pWM5.jpg",
            "release_date":"2022-06-15",
            "title":"버즈 라이트이어",
            "video":false,
            "vote_average":7.2,
            "vote_count":2205
        }],"total_pages":808,"total_results":16150}