export const dummy = {
    "page":1,
    "results":[
        {
            "adult":false,
            "backdrop_path":"/rgZ3hdzgMgYgzvBfwNEVW01bpK1.jpg",
            "genre_ids":[28,53],
            "id":429473,
            "original_language":"en",
            "original_title":"Lou",
            "overview":"반려견과 함께 조용히 살아가던 퉁명스러운 성격의 여인. 폭풍우 속에 이웃의 어린 딸이 납치되자 구조에 나서, 사나운 자연과 어두운 과거에 맞서 격렬한 싸움을 시작한다.",
            "popularity":2280.089,
            "poster_path":"/5F6NM04jwwng3bUE2Q0lGNmFjmw.jpg",
            "release_date":"2022-09-23",
            "title":"루",
            "video":false,
            "vote_average":6.5,
            "vote_count":240
        },
        {
            "adult":false,
            "backdrop_path":"/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
            "genre_ids":[14,12,10751],
            "id":532639,
            "original_language":"en",
            "original_title":"Pinocchio",
            "overview":"목수 ‘제페토’의 간절한 소원으로 태어난 나무 인형 ‘피노키오’는  진짜 사람이 되기 위해 자신의 양심이 되어줄 귀뚜라미 ‘지미니’와 함께  진실되고 용감한 마음을 가지기로 약속한다.  그러나 거리의 교활한 여우의 꾀임에 넘어간 피노키오는 서커스단에 들어가게 되고, 이기적인 어른들의 욕심으로 철장에 갇혀버리고 만다.  한편, 사라진 피노키오를 찾기 위해 길을 나선 ‘제페토’는 폭우 속에 목숨을 잃을 위기에 처하고 마는데…",
            "popularity":1889.804,
            "poster_path":"/aFVjf2zcFzoNgbDKDEHiIw2g1DR.jpg",
            "release_date":"2022-09-08",
            "title":"피노키오",
            "video":false,
            "vote_average":6.7,
            "vote_count":886
        },
        {
            "adult":false,
            "backdrop_path":"/2k9tBql5GYH328Krj66tDT9LtFZ.jpg",
            "genre_ids":[12,18,27],
            "id":760741,
            "original_language":"en",
            "original_title":"Beast",
            "overview":"두 딸 ‘메어’, ‘노라’와 함께 시간을 보내기 위해 친구 ‘마틴’이 있는 남아프리카를 찾은 의사 ‘네이트’. 그러나 즐거운 여행도 잠시, 처참히 죽어 있는 마을 사람들을 목격한 이들은 곧이어 이 모든 상황을 벌인 사자에게 맹목적으로 쫓기기 시작한다. 무전조차 터지지 않는 고립된 지역에서 마을을 완전히 장악해버린 사자로부터 벗어나기 위해 서로 의지하며 고군분투하는데…",
            "popularity":1933.768,
            "poster_path":"/xp6EOh0HEN4bx4ot8UfcYnUpT8U.jpg",
            "release_date":"2022-09-14",
            "title":"비스트",
            "video":false,
            "vote_average":7.1,
            "vote_count":618
        },
        {
            "adult":false,
            "backdrop_path":"/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
            "genre_ids":[14,28,35],
            "id":616037,
            "original_language":"en",
            "original_title":"Thor: Love and Thunder",
            "overview":"이너피스를 위해 자아 찾기 여정을 떠난 천둥의 신 토르. 그러나 우주의 모든 신들을 몰살하려는 신 도살자 고르의 등장으로 토르의 안식년 계획은 산산조각 나 버린다. 토르는새로운 위협에 맞서기 위해 킹 발키리, 코르그, 그리고 전 여자친구 제인과 재회하게 되고, 그녀가 묠니르를 휘두르는 마이티 토르가 되어 나타나 모두를 놀라게 한다. 이제 팀 토르는 고르의 복수에 얽힌 미스터리를 밝히고 더 큰 전쟁을 막기 위한 전 우주적 스케일의 모험을 시작하는데...",
            "popularity":1569.906,
            "poster_path":"/bZLrpWM065h5bu1msUcPmLFsHBe.jpg",
            "release_date":"2022-07-08",
            "title":"토르: 러브 앤 썬더",
            "video":false,
            "vote_average":6.7,
            "vote_count":4134
        },
        {
            "adult":false,
            "backdrop_path":"/qaTzVAW1u16WFNsepjCrilBuInc.jpg",
            "genre_ids":[16,28,10751,35,878],
            "id":539681,
            "original_language":"en",
            "original_title":"DC League of Super-Pets",
            "overview":"악당 렉스 루터의 계략으로 위험에 빠진 슈퍼맨을 비롯한 저스티스 리그의 슈퍼 히어로들을 구하기 위해 슈퍼독 크립토와 슈퍼 펫 친구들이 벌이는 파워 댕댕 모험을 그린 이야기",
            "popularity":1342.385,
            "poster_path":"/4L7hgezinra0QudLN8HPv8c3af1.jpg",
            "release_date":"2022-08-10",
            "title":"DC 리그 오브 슈퍼-펫",
            "video":false,
            "vote_average":7.5,
            "vote_count":786
        },

        {
            "adult":false,
            "backdrop_path":"/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
            "genre_ids":[28,18],
            "id":361743,
            "original_language":"en",
            "original_title":"Top Gun: Maverick",
            "overview":"최고의 파일럿이자 전설적인 인물 매버릭은 자신이 졸업한 훈련학교 교관으로 발탁된다. 그의 명성을 모르던 팀원들은 매버릭의 지시를 무시하지만 실전을 방불케 하는 상공 훈련에서 눈으로 봐도 믿기 힘든 전설적인 조종 실력에 모두가 압도된다. 매버릭의 지휘 아래 견고한 팀워크를 쌓아가던 팀원들에게 국경을 뛰어넘는 위험한 임무가 주어지자 매버릭은 자신이 가르친 동료들과 함께 마지막이 될지 모를 하늘 위 비행에 나서는데...",
            "popularity":1354.323,
            "poster_path":"/jMLiTgCo0vXJuwMzZGoNOUPfuj7.jpg",
            "release_date":"2022-06-22",
            "title":"탑건: 매버릭",
            "video":false,
            "vote_average":8.4,
            "vote_count":4231
        }],"total_pages":807,"total_results":16128}